
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RO = 2;
  public static final int C = 4;
  public static final int PD = 6;
  public static final int ATOM = 9;
  public static final int VARIABLE = 8;
  public static final int EOF = 0;
  public static final int P = 5;
  public static final int RC = 3;
  public static final int error = 1;
  public static final int QD = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RO",
  "RC",
  "C",
  "P",
  "PD",
  "QD",
  "VARIABLE",
  "ATOM"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[2]=new String("RO");
		TT[4]=new String("C");
		TT[6]=new String("PD");
		TT[9]=new String("ATOM");
		TT[8]=new String("VARIABLE");
		TT[0]=new String("EOF");
		TT[5]=new String("P");
		TT[3]=new String("RC");
		TT[1]=new String("error");
		TT[7]=new String("QD");
	}
public String getTT(int i){return TT[i];}
}

