
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ID = 5;
  public static final int CM = 3;
  public static final int error = 1;
  public static final int S = 2;
  public static final int EOF = 0;
  public static final int TYPE = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "S",
  "CM",
  "TYPE",
  "ID"
  };
}

