
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUM = 2;
  public static final int C = 5;
  public static final int SC = 7;
  public static final int INT_TYPE = 9;
  public static final int DOUBLE_TYPE = 10;
  public static final int S = 4;
  public static final int STAR = 8;
  public static final int EOF = 0;
  public static final int ID = 3;
  public static final int SO = 6;
  public static final int error = 1;
  public static final int CHAR_TYPE = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUM",
  "ID",
  "S",
  "C",
  "SO",
  "SC",
  "STAR",
  "INT_TYPE",
  "DOUBLE_TYPE",
  "CHAR_TYPE"
  };
}

