
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUS = 9;
  public static final int S = 6;
  public static final int RO = 2;
  public static final int POW = 14;
  public static final int NUM = 17;
  public static final int RC = 3;
  public static final int uminus = 16;
  public static final int SO = 5;
  public static final int EOF = 0;
  public static final int C = 8;
  public static final int DIV = 12;
  public static final int MINUS = 10;
  public static final int error = 1;
  public static final int SCALARID = 18;
  public static final int EQ = 13;
  public static final int SCALARPROD = 15;
  public static final int SC = 4;
  public static final int VECTORID = 19;
  public static final int MUL = 11;
  public static final int QM = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RO",
  "RC",
  "SC",
  "SO",
  "S",
  "QM",
  "C",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "EQ",
  "POW",
  "SCALARPROD",
  "uminus",
  "NUM",
  "SCALARID",
  "VECTORID"
  };
}

